package com.sidenotes.models

/**
 * Data classes representing the parsed YAML annotation structure
 * generated by the sidenotes Ruby gem.
 */
data class AnnotationData(
    val tableName: String,
    val primaryKey: String,
    val columns: List<ColumnInfo>,
    val indexes: List<IndexInfo>,
    val associations: List<AssociationInfo>
) {
    /**
     * Returns a compact one-line summary for gutter popups.
     */
    fun toSummaryText(): String {
        val colCount = columns.size
        val idxCount = indexes.size
        val assocCount = associations.size
        return "Table: $tableName | $colCount columns, $idxCount indexes, $assocCount associations"
    }

    /**
     * Returns full HTML documentation for Ctrl+Q quick docs.
     */
    fun toHtmlDocumentation(): String = buildString {
        append("<div style='font-family: monospace; font-size: 12px;'>")

        // Header
        append("<h2 style='margin: 0 0 8px 0; color: #6897BB;'>")
        append("Table: <code>$tableName</code></h2>")
        append("<p style='margin: 0 0 12px 0; color: #808080;'>Primary key: <code>$primaryKey</code></p>")

        // Columns table
        append("<h3 style='margin: 12px 0 4px 0; color: #FFC66D;'>Columns</h3>")
        append("<table style='border-collapse: collapse; width: 100%;'>")
        append("<tr style='background: #2B2B2B; color: #A9B7C6;'>")
        append("<th style='padding: 4px 8px; text-align: left; border-bottom: 1px solid #555;'>Name</th>")
        append("<th style='padding: 4px 8px; text-align: left; border-bottom: 1px solid #555;'>Type</th>")
        append("<th style='padding: 4px 8px; text-align: left; border-bottom: 1px solid #555;'>Nullable</th>")
        append("<th style='padding: 4px 8px; text-align: left; border-bottom: 1px solid #555;'>Default</th>")
        append("</tr>")
        for (col in columns) {
            append("<tr>")
            append("<td style='padding: 3px 8px; color: #A9B7C6;'><code>${col.name}</code></td>")
            append("<td style='padding: 3px 8px; color: #CC7832;'>${col.type}</td>")
            append("<td style='padding: 3px 8px; color: ${if (col.nullable) "#6A8759" else "#CC4444"};'>")
            append(if (col.nullable) "yes" else "no")
            append("</td>")
            append("<td style='padding: 3px 8px; color: #808080;'>${col.default ?: ""}</td>")
            append("</tr>")
        }
        append("</table>")

        // Indexes
        if (indexes.isNotEmpty()) {
            append("<h3 style='margin: 12px 0 4px 0; color: #FFC66D;'>Indexes</h3>")
            append("<table style='border-collapse: collapse; width: 100%;'>")
            append("<tr style='background: #2B2B2B; color: #A9B7C6;'>")
            append("<th style='padding: 4px 8px; text-align: left; border-bottom: 1px solid #555;'>Name</th>")
            append("<th style='padding: 4px 8px; text-align: left; border-bottom: 1px solid #555;'>Columns</th>")
            append("<th style='padding: 4px 8px; text-align: left; border-bottom: 1px solid #555;'>Unique</th>")
            append("</tr>")
            for (idx in indexes) {
                append("<tr>")
                append("<td style='padding: 3px 8px; color: #A9B7C6;'><code>${idx.name}</code></td>")
                append("<td style='padding: 3px 8px; color: #6A8759;'>${idx.columns.joinToString(", ")}</td>")
                append("<td style='padding: 3px 8px;'>${if (idx.unique) "✓" else ""}</td>")
                append("</tr>")
            }
            append("</table>")
        }

        // Associations
        if (associations.isNotEmpty()) {
            append("<h3 style='margin: 12px 0 4px 0; color: #FFC66D;'>Associations</h3>")
            append("<table style='border-collapse: collapse; width: 100%;'>")
            append("<tr style='background: #2B2B2B; color: #A9B7C6;'>")
            append("<th style='padding: 4px 8px; text-align: left; border-bottom: 1px solid #555;'>Type</th>")
            append("<th style='padding: 4px 8px; text-align: left; border-bottom: 1px solid #555;'>Name</th>")
            append("<th style='padding: 4px 8px; text-align: left; border-bottom: 1px solid #555;'>Class</th>")
            append("<th style='padding: 4px 8px; text-align: left; border-bottom: 1px solid #555;'>Foreign Key</th>")
            append("</tr>")
            for (assoc in associations) {
                append("<tr>")
                append("<td style='padding: 3px 8px; color: #CC7832;'>${assoc.type}</td>")
                append("<td style='padding: 3px 8px; color: #A9B7C6;'><code>${assoc.name}</code></td>")
                append("<td style='padding: 3px 8px; color: #6897BB;'>${assoc.className}</td>")
                append("<td style='padding: 3px 8px; color: #808080;'>${assoc.foreignKey}</td>")
                append("</tr>")
            }
            append("</table>")
        }

        append("</div>")
    }

    /**
     * Returns plain-text representation for the tool window.
     */
    fun toPlainText(): String = buildString {
        appendLine("Table: $tableName")
        appendLine("Primary Key: $primaryKey")
        appendLine()
        appendLine("── Columns ${"─".repeat(40)}")
        for (col in columns) {
            val nullable = if (col.nullable) "null" else "not null"
            val default = if (col.default != null) ", default: ${col.default}" else ""
            appendLine("  ${col.name.padEnd(24)} ${col.type.padEnd(12)} $nullable$default")
        }
        if (indexes.isNotEmpty()) {
            appendLine()
            appendLine("── Indexes ${"─".repeat(40)}")
            for (idx in indexes) {
                val unique = if (idx.unique) " (unique)" else ""
                appendLine("  ${idx.name}")
                appendLine("    columns: ${idx.columns.joinToString(", ")}$unique")
            }
        }
        if (associations.isNotEmpty()) {
            appendLine()
            appendLine("── Associations ${"─".repeat(35)}")
            for (assoc in associations) {
                appendLine("  ${assoc.type.padEnd(16)} :${assoc.name} → ${assoc.className} (${assoc.foreignKey})")
            }
        }
    }

    /**
     * Find a column by name, case-insensitive.
     */
    fun findColumn(name: String): ColumnInfo? =
        columns.find { it.name.equals(name, ignoreCase = true) }
}

data class ColumnInfo(
    val name: String,
    val type: String,
    val nullable: Boolean,
    val default: String? = null
) {
    /**
     * Returns a short inlay hint string like "string, not null".
     */
    fun toInlayText(): String {
        val parts = mutableListOf(type)
        if (!nullable) parts.add("not null")
        if (default != null) parts.add("default: $default")
        return parts.joinToString(", ")
    }
}

data class IndexInfo(
    val name: String,
    val columns: List<String>,
    val unique: Boolean
)

data class AssociationInfo(
    val type: String,
    val name: String,
    val className: String,
    val foreignKey: String
)
